import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class NumberSorter {

	public static void main(String[] args) {
		System.out.print(printArray(sortNumbers(inputParseToIntArray(inputScanner()))));

	}

	public static String inputScanner() {
		System.out.println("Enter the array of integers.");
		Scanner sc = new Scanner(System.in);
		return sc.nextLine();
	}

	public static String printArray(int[] intArray) {
		String outputSortedString = "Sorted array ascending: ";
		if (intArray == null) {
			return "Please rerun program and enter proper input. Null string not allowed";
		}
		for (int i = 0; i < intArray.length; i++) {
			outputSortedString += intArray[i] + "  ";
		}
		return outputSortedString;
	}

	public static int[] sortNumbers(int[] inputArr) {
		if (inputArr == null) {
			return null;
		}
		int temp;
		for (int i = 0; i < inputArr.length; i++) {
			for (int j = i + 1; j < inputArr.length; j++) {
				if (inputArr[i] > inputArr[j]) {
					temp = inputArr[i];
					inputArr[i] = inputArr[j];
					inputArr[j] = temp;
				}
			}
		}
		return inputArr;
	}

	public static int[] inputParseToIntArray(String str) {
		List<Integer> intArray = new ArrayList<>();
		try {
			String[] strArray = str.split("[ .,;/?!]+");
			for (int i = 0; i < strArray.length; i++) {
				intArray.add(Integer.valueOf(strArray[i]));
			}
			return intArray.stream().mapToInt(i -> i).toArray();
		} catch (NumberFormatException e) {
			System.out.println("Incorrect input string. Separators allowed:  .,;/?!");
			return null;
		}

	}
}
