
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

public class NumberSorterTest {

	@DataProvider(name = "inputsSorted")
	public Object[][] inputsSorted() {
		return new Object[][] {
			{ new int[] { 3, 6, 23, 1 },  "Sorted array ascending: 1  3  6  23  "},
			{ new int[] { 1, 2, 3, 3, 2, 1 },"Sorted array ascending: 1  1  2  2  3  3  "},
			{ new int[] { 23, 75, 12, 1, 0 }, "0Sorted array ascending:   1  12  23  75  "}
			};
	}
	
	@DataProvider(name = "parseString")
	public Object[][] parseString() {
		return new Object[][] {
			{ "3  6  23  1  ", new int[] {3,6,23,1}},
			{ "1  2  3  3  2  1  ", new int[] {1,2,3,3,2,1},},
			{ "23  75  12  1  0  ", new int[] {23,75,12,1,0} },
			{ " , fsxb 23 75 12  1 ,0  ", null },
			{ " , fsxb 23 ....", null }
			};
	}
	
	@DataProvider(name = "inputsPrint")
	public Object[][] inputsPrint() {
		return new Object[][] {
			{ new int[] {3,6,23,1},  "Sorted array ascending: 3  6  23  1  "},
			{ new int[] {1,2,3,3,2,1},"Sorted array ascending: 1  2  3  3  2  1  "},
			{ new int[] {23,75,12,1,0}, "Sorted array ascending: 23  75  12  1  0  "}
			};
	}
	

	@Test(dataProvider = "inputsPrint")
	public void checkPrint(int[] intArray, String output) {
		NumberSorter classUnderTest = new NumberSorter();
		assertEquals(classUnderTest.printArray(intArray), output);
	}

	 @Test(dataProvider = "inputsSorted")
	 public void checkSorting(int[] intArray, String output) {
	 NumberSorter classUnderTest = new NumberSorter();
	 assertEquals(classUnderTest.printArray(classUnderTest.sortNumbers(intArray)), output);
	 }

	 @Test(dataProvider = "parseString")
	 public void checkParsing(String input, int[] parsedArr){
		 NumberSorter classUnderTest = new NumberSorter();
		 assertEquals(classUnderTest.inputParseToIntArray(input), parsedArr);
	 }
}
